language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
